### ISSUE TITLE
Documentation is missing information

### ISSUE THREAD

**Issue by Knight1** [equinix/terraform-provider-metal#104]
Hi!

I wondered long enough to just look into the Provider itself. 

https://github.com/equinix/terraform-provider-metal/blob/main/metal/resource_metal_spot_market_request.go#L50

There are so many instance parameters that are just not on the documentation. 
https://registry.terraform.io/providers/equinix/metal/latest/docs/resources/spot_market_request

I think some folks that are not that Terraform battle proof, like me, would like to have a documentation that reflects whats actually possible with the Terraform Provider.

Thanks!
Tobias

**Comment by t0mk** [comment]
Hi @Knight1, thanks for filling the issue and for the delay of the feedback. You're right that the SMR doc doesn't include the instance params. You can see some of them in the metal_device doc:
https://registry.terraform.io/providers/equinix/metal/latest/docs/resources/device

.. but it's unclear which can be used with the SMR.

I will update the SMR doc this week.
