### ISSUE TITLE
Docs Incorrect with regards to configuration options

### ISSUE THREAD

**Issue by stack72** [equinix/terraform-provider-metal#16]
The docs specify the following https://registry.terraform.io/providers/equinix/equinix/latest/docs#argument-reference

The provider code specifies this - https://github.com/equinix/terraform-provider-metal/blob/main/metal/provider.go#L17

Which is the correct config to use?

**Comment by t0mk** [comment]
hi @stack72, there at (at least) 2 TF providers here in the Equinix github org. I am not sure which one are you trying to use.

There's TF provier Equinix, https://registry.terraform.io/providers/equinix/equinix/ with source at https://github.com/equinix/terraform-provider-equinix

And then there's TF provider for Equinix Metal https://registry.terraform.io/providers/equinix/metal/latest with source in this repo.

HTH

**Comment by stack72** [comment]
Thanks @t0mk 

This was confusion on my part!
