### ISSUE TITLE
Deletion of Metal_Virtual_Connection fails with Error 422

### ISSUE THREAD

**Issue by jbeck-equinix** [equinix/terraform-provider-metal#183]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Affected Resource(s)
Please list the resources as a list, for example:
- metal_virtual_circuit

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

Terraform Configuration Files
```hcl

resource "metal_virtual_circuit" "vc1" {
    connection_id = var.conn_id
    project_id = var.project_id
    port_id = var.port_id
    vlan_id = metal_vlan.vlan1.id
    nni_vlan = var.nni_vlan
}
```

### Debug Output
Get this error message then using equinix metal provider version >= 3.0. When provider version is reverted to 2.1.0, no error messages and virtual connection is deleted as expected. 

metal_virtual_circuit.vc1: Destroying... [id=31e13e9e-57e8-4720-a9b2-a715106a9a8c]
╷
│ Error: PUT https://api.equinix.com/metal/v1/virtual-circuits/31e13e9e-57e8-4720-a9b2-a715106a9a8c: 422 Update params can't be blank 

### Expected Behavior
Virtual Connection gets deleted when `terraform destroy` is run.

### Actual Behavior
Get the error message above when running provider version >=3.0.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` - Everything gets applied as expected
2. `terraform destroy`- action errors out with the warning above.

### Important Factoids
Are there anything atypical about your accounts that we should know?
no

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
no

[terraform.txt](https://github.com/equinix/terraform-provider-metal/files/7108059/terraform.txt)

**Comment by displague** [comment]
@jbeck-equinix this should be fixed in 3.2.0-alpha.4
