### ISSUE TITLE
Device deletion should honor timeout settings

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-metal#216]
The `metal_device` resource should support the Terraform timeout attributes. 

Of particular interest is the timeout for delete events. During a reservation instance deletion the reservation state checking is hardcoded to 60m.

https://github.com/equinix/terraform-provider-metal/blob/main/metal/resource_metal_device.go#L785

The timeout attributes and defaults should be added and documented. The timeout should cover the time to delete the resource and the reservation cleanup.

**Comment by enkelprifti98** [comment]
Just adding terraform docs for reference:

https://www.terraform.io/language/resources/syntax#operation-timeouts
