### ISSUE TITLE
test failure: sweepers should unlock volumes before deleting

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-metal#35]
We should unlock volumes before attempting to delete them.

I suspect the API behavior has changed in some way and this error is surfacing as a side-effect. The result is that our projects are not being fully swept because volumes are not being swept.

`2021/02/12 16:46:12 [ERR] error running (metal_device): Error deleting volume DELETE https://api.equinix.com/metal/v1/storage/c15e6abe-7e36-4f7f-b5dd-1ae339dfb393: 422 Cannot delete a locked item `

**Comment by t0mk** [comment]
volume tests are gone, shall we close this @displague ?
