### ISSUE TITLE
Add a Data Source for VLANs

### ISSUE THREAD

**Issue by enkelprifti98** [equinix/terraform-provider-metal#51]
It would be helpful to have data source for VLANs after they get created. Currently the Terraform provider only has a `VXLAN` attribute for the VLAN resource.

**Comment by displague** [comment]
The `metal_vlan` resource does not have datasource parity, there is no `metal_vlan` datasource.

Implement `metal_vlan` data sources. 
The following fields are available: https://github.com/packethost/packngo/blob/master/virtualnetworks.go#L17-L27

The lookup should be unique and return a single vlan, so lookup should be by ID, (vxlan + metro), or (vxlan + facility).
I don't believe (project + something) creates a unique criteria.

**Comment by displague** [comment]
@enkelprifti98 Of the fields known to packngo, created_at, instances, and href are the only fields I see that are not returned when a VLAN is created. Are these or other fields ones you would expect to have after creating a vlan from a metal_vlan resource?

If the same fields are exposed in a metal_vlan datasource, which fields would you want to perform lookups using? `id` is the only field that jumps out at me, but that also seems like the only field that I would want to use from a datasource. I'm wondering if I'm missing something.

It seems to me that a user that wants a datasource for vlans would want it to get the id, which is the only unique field to look up a vlan by.

Some datasources return multiple results, perhaps you are looking for a datasource metal_vlans that would act this way?

**Comment by enkelprifti98** [comment]
I think those fields are all good to have in the data source.

For performing a lookup, using the `UUID` or `vxlan` value would be useful but at the very least it should be `UUID`.

**Comment by displague** [comment]
Lookup by vxlan makes a lot of sense, especially since you can define it in Metro created VLANs.

**Comment by enkelprifti98** [comment]
Yeah and if it's possible we should allow the lookup to be done by either method, UUID or vxlan, so that the user can choose whichever method they prefer.
