### ISSUE TITLE
no way to lookup ip reservation ids

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-metal#68]
When consuming reservation ids, in a device's ip_address block, the reservation id is a needed field.

It is not currently possible to get the reservation id of an existing reservation.

Perhaps ip_block_ranges should return a structure that includes both the reservation id and the range.

Alternatively, a new ip_reservation datasource could provide this functionality.  Lookups could be by IP Address + Project + Type.

Here is an example of how this could be used:

```hcl 
provider "dns" {}
provider "metal" {}

data "dns_a_record_set" "www" {
  host = "www.example.com"
}

data "metal_reserved_ip_block" "www" {
  project_id = "${var.existing_project}" // required?
  address = data.dns_a_record_set.www.addrs[0] // matches any reservation whose cidr contains this address (optional?)
  // cidr = "" // matches by cidr (optional filter?)
  // type = "public_ipv4" (optional filter?)
  // facility, metro (optional?)

  // error if multiple records match after all filters are applied?
}

resource "metal_device" "www" {
  ip_address {
    type = "public_ipv4"
     // is this an array or a string? docs need updating, they say string but the field is plural  
    reservation_ids = data.metal_reserved_ip_block.www.id  
  }
}
```

Attributes would include everything reported by a [metal_reserved_ip_block resource](https://registry.terraform.io/providers/equinix/metal/latest/docs/resources/reserved_ip_block).

**Comment by displague** [comment]
I'm aware that `metal_ip_attachment` allows for allocation based on CIDR. I would like to be able to map addresses to devices during creation rather than afterward.

**Comment by t0mk** [comment]
Could this be achieved by modyfing datasource precreated_ip_block? It looks up a block reservation based on couple of params:
https://registry.terraform.io/providers/equinix/metal/latest/docs/data-sources/precreated_ip_block#example-usage

At the moment in only has CIDR expression of the found block, but we can add ID there as an attribute.

Also, maybe we should rename it to just "ip_block", and make sure it can look up both precreated blocks and manually reserved blocks.

The `address` filter is a good idea.

I would maybe
* copy datasource metal_precreated_ip_block to a new DS metal_ip_block, add ID to metal_ip_block, maybe add address
* make sure metal_ip_block can lookup both precreated and reserved blocks
* deprecate metal_precreated_ip_block

There might be some technical issue preventing this, maybe I will see it later.

**Comment by displague** [comment]
That sounds reasonable, there should be some parity between the resource and the datasource with the same name, it looks like we would get that.
