### ISSUE TITLE
metal_port_vlan_attachment doesn't work with metro

### ISSUE THREAD

**Issue by t0mk** [equinix/terraform-provider-metal#69]
metal_port_vlan_attachment resource lists all vlans in a project to find a vlan by vxlan. It checks facilities. When using metro, the resource creation fails.

I found this out while wokring on #48 

Culprit code:
https://github.com/equinix/terraform-provider-metal/blob/main/metal/resource_metal_port_vlan_attachment.go#L106

I think just the removal of the facility check should fix it. VXLAN must be unique in a project anyway.

HCL to invoke:
```hcl
resource "metal_device" "web1" {
  hostname         = "web1"
  plan             = "c3.medium.x86"
  metro            = "sv"
  operating_system = "ubuntu_16_04"
  billing_cycle    = "hourly"
  project_id       = local.project_id
}


resource "metal_port_vlan_attachment" "test" {
  device_id = metal_device.web1.id
  port_name = "bond0"
  vlan_vnid = metal_vlan.test.vxlan
}

resource "metal_vlan" "test" {
  project_id       = local.project_id
  metro             = "sv"
  vxlan = 1215
  description       = "ffdfsdf"
}
```

**Comment by displague** [comment]
> I think just the removal of the facility check should fix it. VXLAN must be unique in a project anyway.

That seems reasonable. We could check for either a matching metro or a matching facility, but relying on the unique project makes sense.  I'll verify that this uniqueness can is guaranteed.

**Comment by displague** [comment]
@jordan0day points out:
> a project could have a vlan 1000 in NY and in SG, so you can't count on unique vxlan values for the project

**Comment by jordan0day** [comment]
One other complication is that a project could have, say, a Metro-based VLAN 1000 in Metro NY, a Metro-based VLAN in Metro SG, and maybe a previous facility-based VLAN 1000 in say, facility SJC1.

Facility-based vlans will have a facility, metro-based vlans will have a metro, but they'll never have both, if that helps?

**Comment by t0mk** [comment]
>   a project could have a vlan 1000 in NY and in SG, so you can't count on unique vxlan values for the project

:( I see.

> Facility-based vlans will have a facility, metro-based vlans will have a metro, but they'll never have both, if that helps?

@jordan0day yeah this helps. Thanks!

**Comment by displague** [comment]
We're going to have to address this in the Packet provider too: https://github.com/packethost/terraform-provider-packet/issues/307

**Comment by displague** [comment]
Fixed in https://github.com/equinix/terraform-provider-metal/releases/tag/v2.0.1
