### ISSUE TITLE
metal_facility data source should support filtering by feature flags

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-metal#88]
Module authors that want to enforce facility compatibility with their modules may benefit from feature flag filtering in the facility data source.

For example:

```
data "metal_facility" "hybrid_bonded_check" {
    code = var.facility
    features = ["ibx"] // all features selected must be present to match the facility
}
```

This resource would catch a mis-configuration created by choosing an invalid facility for a configuration that requires hybrid-bonded interfaces.  The error message would not be very helpful, but the configuration would fail much earlier.

**Comment by displague** [comment]
This data source (and metal_metro) could be used to offer https://github.com/equinix/terraform-provider-metal/issues/127:

```
data "metal_facility" "hybrid_bonded_check" {
    code = var.facility
    features = ["ibx"] // all features selected must be present to match the facility

    capacity {
      plan = "c3.small.x86"
      # quantity = 3
      # or
      # level = "normal", this may be the default if quantity or level is not set.
    }
}
```

**Comment by t0mk** [comment]
@displague We could pick facilities with a `filter` blocks like in 
https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/data-sources/regions

That would fix the need for capacity and plan datasources IIUC.
